apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: intro
  name: intro
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: intro
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: intro
    spec:
      containers:
      - env:
        - name: PODIP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: CONFIGVAR
          valueFrom:
            configMapKeyRef:
              key: configvar
              name: intro
        - name: PW
          valueFrom:
            secretKeyRef:
              name: intro
              key: password
        image: intro:0.0.5
        imagePullPolicy: IfNotPresent
        name: intro
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
